FROM python:3.9-slim-buster

WORKDIR /app
ADD . /app

COPY requirements.txt app/requirements.txt

RUN apt-get update && \
    apt-get upgrade -y

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

ENTRYPOINT ["streamlit","run", "app.py"]
