FROM python:3.9-slim-buster

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git libsndfile1 ffmpeg
    
COPY requirements.txt app/requirements.txt

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 8001

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001" , "--reload"]
